// <auto-generated />
using System;
using GestImmo.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestImmo.Migrations
{
    [DbContext(typeof(GestImmoContext))]
    [Migration("20221014092009_GestImmo5")]
    partial class GestImmo5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestImmo.Biens", b =>
                {
                    b.Property<int>("BiensId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BiensId"));

                    b.Property<string>("Adresse")
                        .HasColumnType("text");

                    b.Property<int?>("PretId")
                        .HasColumnType("integer");

                    b.Property<int>("Surface")
                        .HasColumnType("integer");

                    b.Property<int>("Valeur")
                        .HasColumnType("integer");

                    b.HasKey("BiensId");

                    b.HasIndex("PretId");

                    b.ToTable("Bien");
                });

            modelBuilder.Entity("GestImmo.Contrat", b =>
                {
                    b.Property<int>("ContratId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContratId"));

                    b.Property<int?>("BiensId")
                        .HasColumnType("integer");

                    b.Property<string>("DateDebut")
                        .HasColumnType("text");

                    b.Property<string>("DateFin")
                        .HasColumnType("text");

                    b.Property<int>("Loyer")
                        .HasColumnType("integer");

                    b.HasKey("ContratId");

                    b.HasIndex("BiensId");

                    b.ToTable("Contrats");
                });

            modelBuilder.Entity("GestImmo.Intervention", b =>
                {
                    b.Property<int>("InterventionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InterventionId"));

                    b.Property<int>("BiensId")
                        .HasColumnType("integer");

                    b.Property<int>("Date")
                        .HasColumnType("integer");

                    b.Property<string>("Information")
                        .HasColumnType("text");

                    b.Property<int>("MontantTTC")
                        .HasColumnType("integer");

                    b.Property<int?>("PrestataireId")
                        .HasColumnType("integer");

                    b.HasKey("InterventionId");

                    b.HasIndex("BiensId");

                    b.HasIndex("PrestataireId");

                    b.ToTable("Interventions");
                });

            modelBuilder.Entity("GestImmo.Locataire", b =>
                {
                    b.Property<int>("LocataireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocataireId"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("NomLoc")
                        .HasColumnType("text");

                    b.Property<string>("PrenomLoc")
                        .HasColumnType("text");

                    b.Property<string>("Profession")
                        .HasColumnType("text");

                    b.HasKey("LocataireId");

                    b.ToTable("Locataires");
                });

            modelBuilder.Entity("GestImmo.Prestataire", b =>
                {
                    b.Property<int>("PrestataireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PrestataireId"));

                    b.Property<string>("AdresseEntreprise")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .HasColumnType("text");

                    b.Property<string>("RaisonSociale")
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .HasColumnType("text");

                    b.HasKey("PrestataireId");

                    b.ToTable("Prestataires");
                });

            modelBuilder.Entity("GestImmo.Pret", b =>
                {
                    b.Property<int>("PretId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PretId"));

                    b.Property<int>("Apport")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DebutPret")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Duree")
                        .HasColumnType("integer");

                    b.Property<int>("Mensualite")
                        .HasColumnType("integer");

                    b.HasKey("PretId");

                    b.ToTable("Prets");
                });

            modelBuilder.Entity("GestImmo.Box", b =>
                {
                    b.HasBaseType("GestImmo.Biens");

                    b.Property<int>("BoxId")
                        .HasColumnType("integer");

                    b.ToTable("Box", (string)null);
                });

            modelBuilder.Entity("GestImmo.Habitat", b =>
                {
                    b.HasBaseType("GestImmo.Biens");

                    b.Property<int>("Cave")
                        .HasColumnType("integer");

                    b.Property<int>("HabitatId")
                        .HasColumnType("integer");

                    b.Property<int>("NbChambre")
                        .HasColumnType("integer");

                    b.Property<int>("NbPieces")
                        .HasColumnType("integer");

                    b.Property<int>("Parking")
                        .HasColumnType("integer");

                    b.ToTable("Habitat", (string)null);
                });

            modelBuilder.Entity("GestImmo.Appartement", b =>
                {
                    b.HasBaseType("GestImmo.Habitat");

                    b.Property<int>("AppartementId")
                        .HasColumnType("integer");

                    b.Property<int>("Assenceur")
                        .HasColumnType("integer");

                    b.Property<bool>("ChauffCommun")
                        .HasColumnType("boolean");

                    b.Property<int>("Etage")
                        .HasColumnType("integer");

                    b.ToTable("Appartement", (string)null);
                });

            modelBuilder.Entity("GestImmo.Maison", b =>
                {
                    b.HasBaseType("GestImmo.Habitat");

                    b.Property<int>("MaisonId")
                        .HasColumnType("integer");

                    b.ToTable("Maison", (string)null);
                });

            modelBuilder.Entity("GestImmo.Biens", b =>
                {
                    b.HasOne("GestImmo.Pret", "Pret")
                        .WithMany()
                        .HasForeignKey("PretId");

                    b.Navigation("Pret");
                });

            modelBuilder.Entity("GestImmo.Contrat", b =>
                {
                    b.HasOne("GestImmo.Biens", null)
                        .WithMany("ListContrat")
                        .HasForeignKey("BiensId");
                });

            modelBuilder.Entity("GestImmo.Intervention", b =>
                {
                    b.HasOne("GestImmo.Biens", "bien")
                        .WithMany("ListIntervention")
                        .HasForeignKey("BiensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestImmo.Prestataire", null)
                        .WithMany("interventions")
                        .HasForeignKey("PrestataireId");

                    b.Navigation("bien");
                });

            modelBuilder.Entity("GestImmo.Box", b =>
                {
                    b.HasOne("GestImmo.Biens", null)
                        .WithOne()
                        .HasForeignKey("GestImmo.Box", "BiensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestImmo.Habitat", b =>
                {
                    b.HasOne("GestImmo.Biens", null)
                        .WithOne()
                        .HasForeignKey("GestImmo.Habitat", "BiensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestImmo.Appartement", b =>
                {
                    b.HasOne("GestImmo.Habitat", null)
                        .WithOne()
                        .HasForeignKey("GestImmo.Appartement", "BiensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestImmo.Maison", b =>
                {
                    b.HasOne("GestImmo.Habitat", null)
                        .WithOne()
                        .HasForeignKey("GestImmo.Maison", "BiensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestImmo.Biens", b =>
                {
                    b.Navigation("ListContrat");

                    b.Navigation("ListIntervention");
                });

            modelBuilder.Entity("GestImmo.Prestataire", b =>
                {
                    b.Navigation("interventions");
                });
#pragma warning restore 612, 618
        }
    }
}
